=encoding utf8

=head1 NAME

Google::Merchant::Util - helpers for Google::Merchant

=head1 INHERITANCE

 Google::Merchant::Util
   is a Exporter

=head1 SYNOPSIS

  use Google::Merchant::Util ':ns';

=head1 DESCRIPTION

Provide some additional tools and constants to programs which use
L<Google::Merchant|Google::Merchant>.

For now, there is only very little here, but that may grow over time.

=head1 FUNCTIONS

=head2 Export tag :ns10

Exports namespace constants which are useful in the Google-base v1.0
context: NS_GOOGLE_BASE10 and NS_GOOGLE_CUSTOM10.

=head1 SEE ALSO

This module is part of Google-Merchant distribution version 0.15,
built on January 05, 2014. Website: F<http://perl.overmeer.net/xml-compile/>.

=head1 COPYRIGHTS

Copyrights 2013-2014 on the perl code and the related documentation
 by [Mark Overmeer] for StudioSV, The Netherlands.  For other contributors see ChangeLog.

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.
See F<http://www.perl.com/perl/misc/Artistic.html>

